openapi: 3.0.0
info:
  title: Opening Hours REST API
  description: REST API for formatting opening hours of restaurants
  contact:
    name: Viktor Podzigun
    url: https://github.com/viktor-podzigun
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Opening Hours on local
paths:
  /opening-hours/format:
    post:
      tags:
      - opening-hours
      summary: Formats opening hours to human readable format
      operationId: formatOpeningHours
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormatReqDef'
        required: true
      responses:
        default:
          description: Formatted output
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    FormatReqData:
      required:
      - type
      - value
      type: object
      properties:
        type:
          type: string
          enum:
          - open
          - close
        value:
          maximum: 86399
          minimum: 0
          type: integer
          format: int32
    FormatReqDef:
      type: object
      properties:
        monday:
          type: array
          items:
            $ref: '#/components/schemas/FormatReqData'
        tuesday:
          type: array
          items:
            $ref: '#/components/schemas/FormatReqData'
        wednesday:
          type: array
          items:
            $ref: '#/components/schemas/FormatReqData'
        thursday:
          type: array
          items:
            $ref: '#/components/schemas/FormatReqData'
        friday:
          type: array
          items:
            $ref: '#/components/schemas/FormatReqData'
        saturday:
          type: array
          items:
            $ref: '#/components/schemas/FormatReqData'
        sunday:
          type: array
          items:
            $ref: '#/components/schemas/FormatReqData'
